app/S4sme.Web/Areas/Blog/Controllers/CommentController.cs
namespace S4sme.Web.Areas.Blog.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net.Mail;
    using System.Web.Mvc;

    using S4sme.Core.Configuration;
    using S4sme.Core.Services;
    using S4sme.Domain;
    using S4sme.Tasks.Blog;

    public class CommentController : Controller
    {
        private readonly CommentCudTasks commentTasks;

        public CommentController(CommentCudTasks commentTasks)
        {
            this.commentTasks = commentTasks;
        }
        
        [HttpPost]
        /* NOTE: [ValidateAntiForgeryToken] was throwing the exception: System.Web.Mvc.HttpAntiForgeryException. A required anti-forgery token was not supplied or was invalid. */
        public ActionResult Edit(Comment comment)
        {
            if (ModelState.IsValid)
            {
                comment.CreatedDate = DateTime.Now;
                comment.Ip = IpService.GetIpAddress();
                var confirmation = this.commentTasks.SaveOrUpdate(comment);

                if (confirmation.WasSuccessful)
                {
                    EmailService.SendEmail(
                    new MailAddress(Settings.EmailAddress),
                    "New Comment",
                    "S4sme blog - new comment",
                    comment.Content,
                    comment.Avatar);

                    // TempData["message"] = confirmation.Message;
                    return RedirectToAction("Message", "Notification", new { message = Resources.Resource_Blog.MsgCommentsNeedApproval, returnUrl = Url.Action("DetailsById", "Posts", new { id = comment.PostFk }) });
                }

                this.ViewData["message"] = confirmation.Message;
            }

            // we are passing validation errors manually as built-in validation is not working???
            var errors = this.ModelState.Values.SelectMany(modelState => modelState.Errors).Select(error => error.ErrorMessage).ToList();
            this.TempData["Errors"] = errors;
            return RedirectToAction("DetailsById", "Posts", new { id = comment.PostFk });
        }
    }
}

app/S4sme.Web/Areas/Blog/Controllers/PostsController.cs
namespace S4sme.Web.Areas.Blog.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;

    using S4sme.Core.Configuration;
    using S4sme.Domain;
    using S4sme.Domain.Queries.Post;
    using S4sme.Tasks.Blog.ViewModels;

    using SharpLite.Domain.DataInterfaces;

    [HandleError]
    public class PostsController : Controller
    {
        private readonly IRepository<Post> postRepository;

        public PostsController(IRepository<Post> postRepository)
        {
            this.postRepository = postRepository;
        }

        // GET: /Blog/Post/
        public ActionResult Index(int? page)
        {
            var skip = (page.GetValueOrDefault(1) - 1) * Settings.PostsPerPage;

            int postsCount;
            var recentPosts = this.postRepository.GetAll().FindPagedRecentPosts(skip, Settings.PostsPerPage, out postsCount);
            
            var model = new PostIndexViewModel
            {
                CurrentPage = page.GetValueOrDefault(1),
                RecentPosts = recentPosts,
                TotalPages = (int)Math.Ceiling(postsCount / (double)Settings.PostsPerPage)
            };

            ViewBag.Title = Resources.Resource_Blog.BlogName + " - " + Resources.Resource_Blog.BlogDescription;
            ViewBag.Description = Resources.Resource_Blog.BlogDescription;

            if (page.HasValue)
            {
                ViewBag.Title += " - Page " + page.Value;
                ViewBag.Description += " - Page " + page.Value;
            }

            return View(model);
        }

        public virtual ActionResult PostsInTag(string tag, int? page)
        {
            var skip = (page.GetValueOrDefault(1) - 1) * Settings.PostsPerPage;

            int postsCount;
            var recentPosts = this.postRepository.GetAll().FindPagedRecentPosts(skip, Settings.PostsPerPage, out postsCount, tag);
            var model = new PostIndexViewModel
            {
                CurrentPage = page.GetValueOrDefault(1),
                RecentPosts = recentPosts,
                TotalPages = (int)Math.Ceiling(postsCount / (double)Settings.PostsPerPage)
            };

            ViewBag.Title = "All posts tagged '" + tag + "'";
            ViewBag.Description = Resources.Resource_Blog.BlogDescription;

            if (page.HasValue)
            {
                ViewBag.Title += " - Page " + page.Value;
                ViewBag.Description += " - Page " + page.Value;
            }

            return View("Index", model);
        }

        public virtual ActionResult PostsInCategory(string category, int? page)
        {
            var skip = (page.GetValueOrDefault(1) - 1) * Settings.PostsPerPage;

            int postsCount;
            var recentPosts = this.postRepository.GetAll().FindPagedRecentPosts(skip, Settings.PostsPerPage, out postsCount, null, category);
            var model = new PostIndexViewModel
            {
                CurrentPage = page.GetValueOrDefault(1),
                RecentPosts = recentPosts,
                TotalPages = (int)Math.Ceiling(postsCount / (double)Settings.PostsPerPage)
            };

            ViewBag.Title = category;
            ViewBag.Description = Resources.Resource_Blog.BlogDescription;

            if (page.HasValue)
            {
                ViewBag.Title += " - Page " + page.Value;
                ViewBag.Description += " - Page " + page.Value;
            }

            return View("Index", model);
        }

        public ActionResult Details(string slug)
        {
            var post = this.postRepository.GetAll().SingleOrDefault(x => x.Slug == slug);

            if (post == null)
            {
                return this.RedirectToAction("NotFound", "Error", new { area = string.Empty });
            }

            ViewBag.Title = post.Title;
            ViewBag.Keywords = string.Join(",", post.Tags.Select(x => x.Name).Concat(post.Categories.Select(x => x.Name)));
            ViewBag.Description = post.Description;

            return this.View(post);
        }

        /// <summary>
        /// Used for displaying post details after new comment added 
        /// </summary>
        /// <param name="id">id of post</param>
        /// <returns>Action result to Details view</returns>
        public ActionResult DetailsById(int id)
        {
            var post = this.postRepository.Get(id);

            if (post == null)
            {
                return this.RedirectToAction("NotFound", "Error", new { area = string.Empty });
            }

            ViewBag.Title = post.Title;
            ViewBag.Keywords = string.Join(",", post.Tags.Select(x => x.Name).Concat(post.Categories.Select(x => x.Name)));
            ViewBag.Description = post.Description;

            return this.View("Details", post);
        }

        public JsonResult MostRecentPosts()
        {
            int postsCount;
            var recentPosts = this.postRepository.GetAll().FindPagedRecentPosts(0, 2, out postsCount).GetRecentPostsSummary();

            var result = Json(recentPosts, JsonRequestBehavior.AllowGet);

            return result;
        }
    }
}

app/S4sme.Web/Areas/Blog/Views/Posts/Details.cshtml
@using S4sme.Web.Infrastructure.Helpers;
@using S4sme.Core.Configuration;
@model S4sme.Domain.Post

@{
    Layout = "../Shared/_BlogLayout.cshtml";
}

@section Stylesheets {
    <link href="@Url.Content("~/Content/css/prettify/desert.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/css/jquery.lightbox-0.5.css")" rel="stylesheet" type="text/css" />
}

@section Javascripts {
<script type="text/javascript" src="@Url.Content("~/Content/js/prettify/prettify.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Content/js/jquery.lightbox-0.5.js")"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('a.lightbox').lightBox({ fixedNavigation: true });
    });
</script>
}

@section Prettify {onload="prettyPrint()"}

<div id="maincntblog">
    <div class="postcontent">
      <h3>
        @Model.Title</h3>
      <p>
        @Html.Raw(Model.Content)</p>
      <div class="postinfo">Categories: @string.Join(", ", Model.Categories.Select(c => c.Name)) <br />Tags: @string.Join(", ", Model.Tags.Select(c => c.Name))</div>
      <div class="postdate">
        @Model.CreatedDate.ToLongDateString()</div>
    </div>
    <h3 class="commenttitle">
      Showing @Model.Comments.Where(x => x.IsApproved).Count() comments</h3>
    @foreach (var comment in Model.Comments.Where(x => x.IsApproved).OrderBy(x => x.CreatedDate))
    {
      <div class="commentcontent @Html.Raw(Settings.BlogAuthorEmails.Contains(comment.Email) ? "commentalt" : string.Empty)">
       <table class="commentauthor">
        <tbody>
          <tr>
            <td>
              @Html.Raw(Html.Gravatar(comment.Email,90))
            </td>
            <td>
                @if (!string.IsNullOrWhiteSpace(comment.Website)) 
                {
                    <a href="@comment.Website">@comment.Author</a>
                }else { 
                    @comment.Author
                }
                 - <span class="commentauthordate">@comment.CreatedDate.ToLongDateString()</span>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="commentbody">
        @Html.Raw(comment.Content.Replace("\r","<br/>"))</div>
    </div>
    }
    <h3 class="commenttitle">
      Add new comment</h3>
    <div id="commentformarea" class="formbase">
      @if(TempData["Errors"] != null)
      {
          var list = TempData["Errors"] as List<string>;
     <div class="validation-summary-errors"><span>Please correct the following</span>
     <ul>
         @foreach (var error in list) 
         { 
            <li>@error</li>
         }
      </ul></div>
      }
      @*Html.ValidationSummary("Fix the following errors")*@
      @using (Html.BeginForm("Edit", "Comment", FormMethod.Post, new { id = "commentform" })) {
      @Html.Hidden("Comment.PostFk", Model.Id)
      <table id="addcomment">
        <tbody>
          <tr>
            <td colspan="2">
                @Html.Label("Comment.Content","Your comments *")
              <br />
              @Html.TextArea("Comment.Content", null, new {rows="5", cols="40"})
              @*Html.ValidationMessage("Comment.Content", "*")*@
            </td>
          </tr>
          <tr>
            <td>
                @Html.Label("Comment.Author", "Name *")
              <br />
              @Html.TextBox("Comment.Author", null, new {@class="comment"})
              @*Html.ValidationMessage("Comment.Author", "*")*@
            </td>
            <td>
            @Html.Label("Comment.Email", "Email *")
              <br />
                @Html.TextBox("Comment.Email", null, new { @class = "comment" })
              @*Html.ValidationMessage("Comment.Email", "*")*@
            </td>
          </tr>
          <tr>
            <td>
            @Html.Label("Comment.Website", "Website (optional):")
              <br />
              @Html.TextBox("Comment.Website", null, new {@class="comment"})
              @*Html.ValidationMessage("Comment.Website", "*")*@
            </td>
            <td>
              <br />
              @Html.CheckBox("Comment.Subscribe")
              Subscribe to all comments by email
            </td>
          </tr>
          <tr><td><input type="submit" id="commentsubmit" class="btnsubmit" value="Submit Comment &gt;&gt;"/></td></tr>
        </tbody>
      </table>
      }
    </div>
  </div>

@*
<asp:Content ID="rightbar" ContentPlaceHolderID="RightBarContent" runat="server">
  <%Html.RenderPartial("RightBar", Model.RightBarData); %>
</asp:Content>
*@
@*
<asp:Content ID="scriptholderid" ContentPlaceHolderID="ScriptPlaceHolder" runat="server">
<script type="text/javascript" src="<%= Url.Content("~/content/js/shCore.js") %>"></script>
<script type="text/javascript" src="<%= Url.Content("~/content/js//shBrushCSharp.js") %>"></script>
<script type="text/javascript" src="<%= Url.Content("~/content/js/shBrushCss.js") %>"></script>
<script type="text/javascript" src="<%= Url.Content("~/content/js/shBrushXml.js") %>"></script>
<script type="text/javascript" src="<%= Url.Content("~/content/js/shBrushJScript.js") %>"></script>
  <script type="text/javascript">
      SyntaxHighlighter.config.clipboardSwf = '<%= Url.Content("~/content/js/clipboard.swf") %>';
      SyntaxHighlighter.all();
	</script>
</asp:Content>
*@

app/S4sme.Web/Areas/Blog/Views/Posts/Index.cshtml
@using S4sme.Web.Resources;
@using System.Collections.Specialized;
@model S4sme.Tasks.Blog.ViewModels.PostIndexViewModel

@{
    ViewBag.Keywords = Resource_Blog.BlogKeyWords;
    Layout = "../Shared/_BlogLayout.cshtml";
}

@helper Links(int currentPage, int totalPages, string previousPageText, string nextPageText) {

bool hasMorePages = currentPage < totalPages;
bool hasPrevPages = currentPage > 1;


<p class="morelink">

@if (hasPrevPages)
{
     <span class="leftfloat">&lt;&lt;&lt;@Html.ActionLink(previousPageText, "Index", new { page = currentPage - 1 })</span>
}

@if (hasMorePages)
{
     <span class="rightfloat">@Html.ActionLink(nextPageText, "Index", new { page = currentPage + 1 })&gt;&gt;&gt;</span>
}

</p>
}

<div id="maincntblog">

@foreach (var item in Model.RecentPosts)
{
    <div class="postcontent">
      <h3>
        <a href="@Url.Action("Details", "Posts",
             new
             {
                 slug = item.Slug
             })"
          rel="bookmark" title="Permanent Link to @item.Title">@item.Title</a></h3>      
      <div class="postbody">
        @item.Description
       </div>
       <div class="postinfo">Categories: @string.Join(", ", item.Categories.Select(c => c.Name)) <br />Tags: @string.Join(", ", item.Tags.Select(c => c.Name))</div>
      <div class="postdate">
        @item.CreatedDate.ToLongDateString()</div>
    </div>
}

@Links(Model.CurrentPage, Model.TotalPages, Resource_Blog.PreviousLink, Resource_Blog.MoreLink)

</div>