app/S4sme.Web/Areas/Blog/Controllers/CategoryController.cs
namespace S4sme.Web.Areas.Blog.Controllers
{
    using System.Linq;
    using System.Web.Mvc;

    using S4sme.Domain;

    using SharpLite.Domain.DataInterfaces;

    public class CategoryController : Controller
    {
        private readonly IRepository<Category> categoryRepository;

        public CategoryController(IRepository<Category> categoryRepository)
        {
            this.categoryRepository = categoryRepository;
        }

        // will be used as widget
        public ActionResult List()
        {
            return this.PartialView(this.categoryRepository.GetAll().OrderBy(pc => pc.Name));
        }
    }
}

app/S4sme.Web/Areas/Blog/Controllers/PostsController.cs
namespace S4sme.Web.Areas.Blog.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;

    using S4sme.Core.Configuration;
    using S4sme.Domain;
    using S4sme.Domain.Queries.Post;
    using S4sme.Tasks.Blog.ViewModels;

    using SharpLite.Domain.DataInterfaces;

    [HandleError]
    public class PostsController : Controller
    {
        private readonly IRepository<Post> postRepository;

        public PostsController(IRepository<Post> postRepository)
        {
            this.postRepository = postRepository;
        }

        // GET: /Blog/Post/
        public ActionResult Index(int? page)
        {
            var skip = (page.GetValueOrDefault(1) - 1) * Settings.PostsPerPage;

            int postsCount;
            var recentPosts = this.postRepository.GetAll().FindPagedRecentPosts(skip, Settings.PostsPerPage, out postsCount);
            
            var model = new PostIndexViewModel
            {
                CurrentPage = page.GetValueOrDefault(1),
                RecentPosts = recentPosts,
                TotalPages = (int)Math.Ceiling(postsCount / (double)Settings.PostsPerPage)
            };

            ViewBag.Title = Resources.Resource_Blog.BlogName + " - " + Resources.Resource_Blog.BlogDescription;
            ViewBag.Description = Resources.Resource_Blog.BlogDescription;

            if (page.HasValue)
            {
                ViewBag.Title += " - Page " + page.Value;
                ViewBag.Description += " - Page " + page.Value;
            }

            return View(model);
        }

        public virtual ActionResult PostsInTag(string tag, int? page)
        {
            var skip = (page.GetValueOrDefault(1) - 1) * Settings.PostsPerPage;

            int postsCount;
            var recentPosts = this.postRepository.GetAll().FindPagedRecentPosts(skip, Settings.PostsPerPage, out postsCount, tag);
            var model = new PostIndexViewModel
            {
                CurrentPage = page.GetValueOrDefault(1),
                RecentPosts = recentPosts,
                TotalPages = (int)Math.Ceiling(postsCount / (double)Settings.PostsPerPage)
            };

            ViewBag.Title = "All posts tagged '" + tag + "'";
            ViewBag.Description = Resources.Resource_Blog.BlogDescription;

            if (page.HasValue)
            {
                ViewBag.Title += " - Page " + page.Value;
                ViewBag.Description += " - Page " + page.Value;
            }

            return View("Index", model);
        }

        public virtual ActionResult PostsInCategory(string category, int? page)
        {
            var skip = (page.GetValueOrDefault(1) - 1) * Settings.PostsPerPage;

            int postsCount;
            var recentPosts = this.postRepository.GetAll().FindPagedRecentPosts(skip, Settings.PostsPerPage, out postsCount, null, category);
            var model = new PostIndexViewModel
            {
                CurrentPage = page.GetValueOrDefault(1),
                RecentPosts = recentPosts,
                TotalPages = (int)Math.Ceiling(postsCount / (double)Settings.PostsPerPage)
            };

            ViewBag.Title = category;
            ViewBag.Description = Resources.Resource_Blog.BlogDescription;

            if (page.HasValue)
            {
                ViewBag.Title += " - Page " + page.Value;
                ViewBag.Description += " - Page " + page.Value;
            }

            return View("Index", model);
        }

        public ActionResult Details(string slug)
        {
            var post = this.postRepository.GetAll().SingleOrDefault(x => x.Slug == slug);

            if (post == null)
            {
                return this.RedirectToAction("NotFound", "Error", new { area = string.Empty });
            }

            ViewBag.Title = post.Title;
            ViewBag.Keywords = string.Join(",", post.Tags.Select(x => x.Name).Concat(post.Categories.Select(x => x.Name)));
            ViewBag.Description = post.Description;

            return this.View(post);
        }

        /// <summary>
        /// Used for displaying post details after new comment added 
        /// </summary>
        /// <param name="id">id of post</param>
        /// <returns>Action result to Details view</returns>
        public ActionResult DetailsById(int id)
        {
            var post = this.postRepository.Get(id);

            if (post == null)
            {
                return this.RedirectToAction("NotFound", "Error", new { area = string.Empty });
            }

            ViewBag.Title = post.Title;
            ViewBag.Keywords = string.Join(",", post.Tags.Select(x => x.Name).Concat(post.Categories.Select(x => x.Name)));
            ViewBag.Description = post.Description;

            return this.View("Details", post);
        }

        public JsonResult MostRecentPosts()
        {
            int postsCount;
            var recentPosts = this.postRepository.GetAll().FindPagedRecentPosts(0, 2, out postsCount).GetRecentPostsSummary();

            var result = Json(recentPosts, JsonRequestBehavior.AllowGet);

            return result;
        }
    }
}

app/S4sme.Web/Areas/Blog/Controllers/TagController.cs
namespace S4sme.Web.Areas.Blog.Controllers
{
    using System.Linq;
    using System.Web.Mvc;

    using S4sme.Domain;

    using SharpLite.Domain.DataInterfaces;

    public class TagController : Controller
    {
        private readonly IRepository<Tag> tagRepository;

        private readonly IRepository<Post> postRepository;


        public TagController(IRepository<Tag> tagRepository, IRepository<Post> postRepository)
        {
            this.tagRepository = tagRepository;
            this.postRepository = postRepository;
        }

        // will be used as widget
        public ActionResult List()
        {
            ViewBag.TotalPosts = this.postRepository.GetAll().Count(); // TODO: should filter by IsPublished
            return this.PartialView(this.tagRepository.GetAll().OrderBy(t => t.Name));
        }
    }
}

app/S4sme.Web/Controllers/Shared/ErrorController.cs
namespace S4sme.Web.Controllers.Shared
{
    using System.Web.Mvc;

    public class ErrorController : Controller
    {
        public ActionResult Error()
        {
            return View();
        }

        public ActionResult NotFound()
        {
            return View();
        }
    }
}

app/S4sme.Web/Areas/Blog/Views/Shared/Message.cshtml
@using S4sme.Web.Resources;
@{
    Layout = "../Shared/_BlogLayout.cshtml";
    ViewBag.Title = Resource_Blog.BlogName + " Message page";
    ViewBag.Keywords = Resource_Blog.BlogKeyWords;
    ViewBag.Description = Resource_Blog.BlogDescription;
}

<div id="maincntblog">
	<div id="content" style="height:400px">
		<h2 style="margin: 100px auto; text-align:center; background:gray; padding: 50px 10px">@ViewBag.Message</h2>
        <p><a href="@ViewBag.ReturnUrl" >@Resource_Common.ReturnLink</a></p>				
	</div>
</div>


app/S4sme.Web/Areas/Blog/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
    @RenderSection("Stylesheets", false)
</head>

<body>
    <div id="mainContent">
        @if (TempData["message"] != null) {
            <div class="message">@TempData["message"]</div>
        }

        @if (ViewData["message"] != null) {
            <div class="message">@ViewData["message"]</div>
        }

        @RenderBody()
    </div>
</body>
</html>

app/S4sme.Web/Areas/Blog/Views/Shared/_BlogLayout.cshtml
@using S4sme.Web.Resources;
@using S4sme.Web.Infrastructure.Globalisation;
@using S4sme.Core.Configuration;
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>@ViewBag.Title</title>
    <link href="http://yui.yahooapis.com/3.0.0/build/cssreset/reset-min.css" rel="stylesheet"
        type="text/css" />
    <link href="@Url.Content("~/Themes/" + Settings.CurrentTheme + "/Content/css/main.css")" rel="stylesheet" type="text/css" />
    @RenderSection("Stylesheets", false)
    <link rel="icon" href="@Url.Content("~/favicon.ico")" />
    <meta name="title" content="@ViewBag.Title" />
    <meta name="keywords" content="@ViewBag.Keywords" />
    <meta name="description" content="@ViewBag.Description" />
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
    <meta content="Global" name="Distribution" />
    <meta content="@Resource_Common.SiteAuthor" name="Author" />
</head>
<body @RenderSection("Prettify", false)>
    <div id="page" class="pageblogbg">
        <div id="wrapperblog" class="wrap">
            <div id="header">
                <div id="lang">
                 <a href="@Url.GlobalisedRouteUrl("ru", ViewContext.RouteData, ViewContext.HttpContext.Request.QueryString)" title="@Resource_Common.LangRu">
                    <img alt="ru" src="@Url.Content("~/Themes/" + Settings.CurrentTheme + "/content/img/ru.gif")" />
                 </a>&nbsp; 
                 <a href="@Url.GlobalisedRouteUrl("en", ViewContext.RouteData, ViewContext.HttpContext.Request.QueryString)" title="@Resource_Common.LangEn">
                    <img alt="en" src="@Url.Content("~/Themes/" + Settings.CurrentTheme + "/content/img/gb.gif")" />
                 </a>
                </div>
                <div id="nav">
                    <span id="logo">
                        <img alt="logo" src="@Url.Content("~/Themes/" + Settings.CurrentTheme + "/content/img/logo_03.gif")" /></span>
                    <ul>
                        <li>
                            @Html.ActionLink(Resource_Common.MainNavHome, "Index", "Home", new { area = "" }, null)
                        </li>
                        <li>
                            @Html.ActionLink(Resource_Common.MainNavBlog, "Index", "Posts", new { area = "Blog" }, new { id = "current" })
                        </li>
                    </ul>
                </div>
            </div>
            <div id="submenu">
                <div id="submenuframe">
                @{ var actionName = ViewContext.RouteData.Values["action"].ToString(); }
                    <ul>
                        <li>@Html.ActionLink(Resource_Blog.SubNavArchive, "Index", "Posts", new { area = "Blog" }, actionName == "Index" ? new { id = "subcurrent" } : null)</li>
                        <li>@Html.ActionLink(Resource_Blog.SubNavProjects, "Projects", "About", new { area = "Blog" }, actionName == "Projects" ? new { id = "subcurrent" } : null)</li>
                        <li>@Html.ActionLink(Resource_Blog.SubNavCv, "Cv", "About", new { area = "Blog" }, actionName == "Cv" ? new { id = "subcurrent" } : null)</li>
                        <li>@Html.ActionLink(Resource_Blog.SubNavContact, "Contact", "About", new { area = "Blog" }, actionName == "Contact" ? new { id = "subcurrent" } : null)</li>
                    </ul>
                </div>
            </div>
            @RenderBody()
            <div id="wrapperfooter">
                <div id="footerblog">
                    <div id="footercontent">
                        <p>
                            S4SME.com &copy;
                            @Resource_Common.Сopyright
                        </p>
                        <br />
                        <p class="horAd">
                            <script type="text/javascript"><!--
                                google_ad_client = "pub-9186582526578916";
                                google_ad_slot = "2642369506";
                                google_ad_width = 468;
                                google_ad_height = 60;
                //-->
                            </script>
                            <script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
                            </script>
                        </p>
                    </div>
                </div>
            </div>
            <div id="staticblog" class="static">
                <div id="searchcntrl">
                    <img alt="search" src="@Url.Content("~/Themes/" + Settings.CurrentTheme + "/content/img/search.gif")" /><span>@Resource_Blog.SearchBlog</span><br />
                    <p id="searchinput">
                        <input id="searchinputcntrl" type="text" onkeyup="if (this.value) {searchwords(this.value)} else {clearresults()}" /></p>
                    <small>
                        @Resource_Blog.SearchNote</small>
                </div>
                @*<asp:ContentPlaceHolder ID="RightBarContent" runat="server" />*@
                <div class="sectiontitle">
                    About</div>
                <div class="sectionitem" style="">
                    <div class="sectiontextcontent wrappedtext colorGR">
                        <img class="leftfloat wrappedimg2" src="@Url.Content("~/Themes/" + Settings.CurrentTheme + "/content/img/myimg.gif")" alt="Personal image"
                            width="130" />
                        My name is Sergey Kosik. I am a software engineer and write this blog about software
                        development, design, and architecture to solve business problems...
                        <br />
                    </div>
                    <span class="readmore">@Html.ActionLink(Resource_Blog.ProfileLink, "Profile", "About", new { area = "Blog" }, null)</span>
                </div>
                <div class="clr"></div>

                @Html.Action("List", "Category")
                @Html.Action("List", "Tag")
                
                <div class="sectiontitle">
                    Disclaimer</div>
                <div class="sectionitem">
                    <p class="sectiontextcontent colorWT">
                        Everything you see in this blog is my own personal opinion, based on my experience
                        in the software field.
                        <br />
                        <br />
                        It should also be noted that all software downloaded from this site provided "AS-IS"
                        with no warranties, and confer no rights.
                        <br />
                    </p>
                </div>
                <div class="sectionitem">
        <br />
        <script type="text/javascript"><!--
            google_ad_client = "pub-9186582526578916";
            google_ad_slot = "9069567704";
            google_ad_width = 200;
            google_ad_height = 90;
          //-->
          </script>
          <script type="text/javascript"
          src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
          </script>
        </div>
                @* end of rightbarcontent *@
            </div>
        </div>
    </div>
    
  <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.6.2.js" type="text/javascript"></script>
  @RenderSection("Javascripts", false)
  <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-30206085-1']);
      _gaq.push(['_trackPageview']);

      (function () {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
</script>
  @*
  <script type="text/javascript" src="/content/js/utils.js"></script>
  <script type="text/javascript" src="/content/js/jquery.highlight-3.yui.js"></script>
  <script type="text/javascript">
      $(document).ready(function () {
          qsParm = getQueryStringArgs();
          if (qsParm["srch"] != undefined)
              $('#maincntblog').highlight(qsParm["srch"]);
      });
  </script>*@
  
</body>
</html>