app/S4sme.Web/Areas/Blog/Controllers/AdminController.cs
namespace S4sme.Web.Areas.Blog.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;

    using S4sme.Core.Extensions;
    using S4sme.Domain;
    using S4sme.Tasks.Blog;

    using SharpLite.Domain.DataInterfaces;

    public class AdminController : AuthorizeBaseController
    {
        private readonly IRepository<Post> postRepository;

        private readonly IRepository<Category> categoryRepository;

        private readonly IRepository<Tag> tagRepository;

        private readonly IRepository<Comment> commentRepository;

        private readonly PostCudTasks postTasks;

        private readonly CategoryCudTasks categoryTasks;

        private readonly TagCudTasks tagTasks;

        private readonly CommentCudTasks commentTasks;

        public AdminController(IRepository<Post> postRepository, IRepository<Category> categoryRepository, IRepository<Tag> tagRepository, IRepository<Comment> commentRepository, PostCudTasks postTasks, CategoryCudTasks categoryTasks, TagCudTasks tagTasks, CommentCudTasks commentTasks)
        {
            this.postRepository = postRepository;
            this.categoryRepository = categoryRepository;
            this.tagRepository = tagRepository;
            this.commentRepository = commentRepository;
            this.postTasks = postTasks;
            this.categoryTasks = categoryTasks;
            this.tagTasks = tagTasks;
            this.commentTasks = commentTasks;
        }

        //
        // GET: /Blog/Admin/

        public ActionResult Posts()
        {
            var posts = this.postRepository.GetAll();
            return View(posts);
        }

        public ActionResult CreatePost()
        {
            return this.View("EditPost", this.postTasks.CreateEditViewModel());
        }

        public ActionResult EditPost(int id)
        {
            return View(this.postTasks.CreateEditViewModel(id));
        }

        [HttpPost]
        /*[ValidateInput(false)]  allows HTML markup */
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(Post post)
        {
            if (ModelState.IsValid)
            {
                // will be used only once the new post created
                post.Author = HttpContext.User.Identity.Name;
                post.CreatedDate = DateTime.Now;
                post.ModifiedDate = post.CreatedDate;
                post.Slug = post.Title.GenerateSlug();

                ActionConfirmation<Post> confirmation = this.postTasks.SaveOrUpdate(post);

                if (confirmation.WasSuccessful)
                {
                    TempData["message"] = confirmation.Message;
                    return RedirectToAction("Posts");
                }

                ViewData["message"] = confirmation.Message;
            }

            return View(this.postTasks.CreateEditViewModel(post));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            ActionConfirmation<Post> confirmation = this.postTasks.Delete(id);
            TempData["message"] = confirmation.Message;
            return RedirectToAction("Posts");
        }

        public ActionResult Categories()
        {
            return View(this.categoryRepository.GetAll().OrderBy(pc => pc.Name));
        }

        public ActionResult CreateCategory()
        {
            return this.View("EditCategory", this.categoryTasks.CreateEditViewModel());
        }

        public ActionResult EditCategory(int id)
        {
            return View(this.categoryTasks.CreateEditViewModel(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCategory(Category category)
        {
            if (ModelState.IsValid)
            {
                var confirmation = this.categoryTasks.SaveOrUpdate(category);

                if (confirmation.WasSuccessful)
                {
                    TempData["message"] = confirmation.Message;
                    return RedirectToAction("Categories");
                }

                ViewData["message"] = confirmation.Message;
            }

            return View(this.categoryTasks.CreateEditViewModel(category));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteCategory(int id)
        {
            var confirmation = this.categoryTasks.Delete(id);
            TempData["message"] = confirmation.Message;
            return RedirectToAction("Categories");
        }

        public ActionResult Tags()
        {
            return View(this.tagRepository.GetAll().OrderBy(t => t.Name));
        }

        public ActionResult CreateTag()
        {
            return this.View("EditTag", this.tagTasks.CreateEditViewModel());
        }

        public ActionResult EditTag(int id)
        {
            return View(this.tagTasks.CreateEditViewModel(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditTag(Tag tag)
        {
            if (ModelState.IsValid)
            {
                var confirmation = this.tagTasks.SaveOrUpdate(tag);

                if (confirmation.WasSuccessful)
                {
                    TempData["message"] = confirmation.Message;
                    return RedirectToAction("Tags");
                }

                ViewData["message"] = confirmation.Message;
            }

            return View(this.tagTasks.CreateEditViewModel(tag));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteTag(int id)
        {
            var confirmation = this.tagTasks.Delete(id);
            TempData["message"] = confirmation.Message;
            return RedirectToAction("Tags");
        }

        public ActionResult Comments()
        {
            return View(this.commentRepository.GetAll().OrderBy(c => c.CreatedDate));
        }

        public ActionResult CreateComment()
        {
            var viewModel = this.commentTasks.CreateEditViewModel();

            return this.View("EditComment", viewModel);
        }

        public ActionResult EditComment(int id)
        {
            return View(this.commentTasks.CreateEditViewModel(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditComment(Comment comment)
        {
            if (ModelState.IsValid)
            {
                var confirmation = this.commentTasks.SaveOrUpdate(comment);

                if (confirmation.WasSuccessful)
                {
                    TempData["message"] = confirmation.Message;
                    return RedirectToAction("Comments");
                }

                ViewData["message"] = confirmation.Message;
            }

            return View(this.commentTasks.CreateEditViewModel(comment));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteComment(int id)
        {
            var confirmation = this.commentTasks.Delete(id);
            TempData["message"] = confirmation.Message;
            return RedirectToAction("Comments");
        }
    }
}

app/S4sme.Web/Areas/Blog/Controllers/CommentController.cs
namespace S4sme.Web.Areas.Blog.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net.Mail;
    using System.Web.Mvc;

    using S4sme.Core.Configuration;
    using S4sme.Core.Services;
    using S4sme.Domain;
    using S4sme.Tasks.Blog;

    public class CommentController : Controller
    {
        private readonly CommentCudTasks commentTasks;

        public CommentController(CommentCudTasks commentTasks)
        {
            this.commentTasks = commentTasks;
        }
        
        [HttpPost]
        /* NOTE: [ValidateAntiForgeryToken] was throwing the exception: System.Web.Mvc.HttpAntiForgeryException. A required anti-forgery token was not supplied or was invalid. */
        public ActionResult Edit(Comment comment)
        {
            if (ModelState.IsValid)
            {
                comment.CreatedDate = DateTime.Now;
                comment.Ip = IpService.GetIpAddress();
                var confirmation = this.commentTasks.SaveOrUpdate(comment);

                if (confirmation.WasSuccessful)
                {
                    EmailService.SendEmail(
                    new MailAddress(Settings.EmailAddress),
                    "New Comment",
                    "S4sme blog - new comment",
                    comment.Content,
                    comment.Avatar);

                    // TempData["message"] = confirmation.Message;
                    return RedirectToAction("Message", "Notification", new { message = Resources.Resource_Blog.MsgCommentsNeedApproval, returnUrl = Url.Action("DetailsById", "Posts", new { id = comment.PostFk }) });
                }

                this.ViewData["message"] = confirmation.Message;
            }

            // we are passing validation errors manually as built-in validation is not working???
            var errors = this.ModelState.Values.SelectMany(modelState => modelState.Errors).Select(error => error.ErrorMessage).ToList();
            this.TempData["Errors"] = errors;
            return RedirectToAction("DetailsById", "Posts", new { id = comment.PostFk });
        }
    }
}

app/S4sme.Web/Areas/Blog/Controllers/PostsController.cs
namespace S4sme.Web.Areas.Blog.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;

    using S4sme.Core.Configuration;
    using S4sme.Domain;
    using S4sme.Domain.Queries.Post;
    using S4sme.Tasks.Blog.ViewModels;

    using SharpLite.Domain.DataInterfaces;

    [HandleError]
    public class PostsController : Controller
    {
        private readonly IRepository<Post> postRepository;

        public PostsController(IRepository<Post> postRepository)
        {
            this.postRepository = postRepository;
        }

        // GET: /Blog/Post/
        public ActionResult Index(int? page)
        {
            var skip = (page.GetValueOrDefault(1) - 1) * Settings.PostsPerPage;

            int postsCount;
            var recentPosts = this.postRepository.GetAll().FindPagedRecentPosts(skip, Settings.PostsPerPage, out postsCount);
            
            var model = new PostIndexViewModel
            {
                CurrentPage = page.GetValueOrDefault(1),
                RecentPosts = recentPosts,
                TotalPages = (int)Math.Ceiling(postsCount / (double)Settings.PostsPerPage)
            };

            ViewBag.Title = Resources.Resource_Blog.BlogName + " - " + Resources.Resource_Blog.BlogDescription;
            ViewBag.Description = Resources.Resource_Blog.BlogDescription;

            if (page.HasValue)
            {
                ViewBag.Title += " - Page " + page.Value;
                ViewBag.Description += " - Page " + page.Value;
            }

            return View(model);
        }

        public virtual ActionResult PostsInTag(string tag, int? page)
        {
            var skip = (page.GetValueOrDefault(1) - 1) * Settings.PostsPerPage;

            int postsCount;
            var recentPosts = this.postRepository.GetAll().FindPagedRecentPosts(skip, Settings.PostsPerPage, out postsCount, tag);
            var model = new PostIndexViewModel
            {
                CurrentPage = page.GetValueOrDefault(1),
                RecentPosts = recentPosts,
                TotalPages = (int)Math.Ceiling(postsCount / (double)Settings.PostsPerPage)
            };

            ViewBag.Title = "All posts tagged '" + tag + "'";
            ViewBag.Description = Resources.Resource_Blog.BlogDescription;

            if (page.HasValue)
            {
                ViewBag.Title += " - Page " + page.Value;
                ViewBag.Description += " - Page " + page.Value;
            }

            return View("Index", model);
        }

        public virtual ActionResult PostsInCategory(string category, int? page)
        {
            var skip = (page.GetValueOrDefault(1) - 1) * Settings.PostsPerPage;

            int postsCount;
            var recentPosts = this.postRepository.GetAll().FindPagedRecentPosts(skip, Settings.PostsPerPage, out postsCount, null, category);
            var model = new PostIndexViewModel
            {
                CurrentPage = page.GetValueOrDefault(1),
                RecentPosts = recentPosts,
                TotalPages = (int)Math.Ceiling(postsCount / (double)Settings.PostsPerPage)
            };

            ViewBag.Title = category;
            ViewBag.Description = Resources.Resource_Blog.BlogDescription;

            if (page.HasValue)
            {
                ViewBag.Title += " - Page " + page.Value;
                ViewBag.Description += " - Page " + page.Value;
            }

            return View("Index", model);
        }

        public ActionResult Details(string slug)
        {
            var post = this.postRepository.GetAll().SingleOrDefault(x => x.Slug == slug);

            if (post == null)
            {
                return this.RedirectToAction("NotFound", "Error", new { area = string.Empty });
            }

            ViewBag.Title = post.Title;
            ViewBag.Keywords = string.Join(",", post.Tags.Select(x => x.Name).Concat(post.Categories.Select(x => x.Name)));
            ViewBag.Description = post.Description;

            return this.View(post);
        }

        /// <summary>
        /// Used for displaying post details after new comment added 
        /// </summary>
        /// <param name="id">id of post</param>
        /// <returns>Action result to Details view</returns>
        public ActionResult DetailsById(int id)
        {
            var post = this.postRepository.Get(id);

            if (post == null)
            {
                return this.RedirectToAction("NotFound", "Error", new { area = string.Empty });
            }

            ViewBag.Title = post.Title;
            ViewBag.Keywords = string.Join(",", post.Tags.Select(x => x.Name).Concat(post.Categories.Select(x => x.Name)));
            ViewBag.Description = post.Description;

            return this.View("Details", post);
        }

        public JsonResult MostRecentPosts()
        {
            int postsCount;
            var recentPosts = this.postRepository.GetAll().FindPagedRecentPosts(0, 2, out postsCount).GetRecentPostsSummary();

            var result = Json(recentPosts, JsonRequestBehavior.AllowGet);

            return result;
        }
    }
}

app/S4sme.Web/Areas/Blog/Controllers/TagController.cs
namespace S4sme.Web.Areas.Blog.Controllers
{
    using System.Linq;
    using System.Web.Mvc;

    using S4sme.Domain;

    using SharpLite.Domain.DataInterfaces;

    public class TagController : Controller
    {
        private readonly IRepository<Tag> tagRepository;

        private readonly IRepository<Post> postRepository;


        public TagController(IRepository<Tag> tagRepository, IRepository<Post> postRepository)
        {
            this.tagRepository = tagRepository;
            this.postRepository = postRepository;
        }

        // will be used as widget
        public ActionResult List()
        {
            ViewBag.TotalPosts = this.postRepository.GetAll().Count(); // TODO: should filter by IsPublished
            return this.PartialView(this.tagRepository.GetAll().OrderBy(t => t.Name));
        }
    }
}

app/S4sme.Web/Areas/Blog/Views/Admin/Categories.cshtml
@model IEnumerable<S4sme.Domain.Category>
           
@{
    ViewBag.Title = "Index";
}

<h2>Category List</h2>

<table>
    <tr>
        <th>
            Name
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @item.Name
            </td>
            <td>
                @Html.ActionLink("Edit", "EditCategory", new { id = item.Id }) |
                
                @using (Html.BeginForm("DeleteCategory", "Admin", FormMethod.Post, new { style = "display:inline" })) {
                    @Html.AntiForgeryToken()
                    @Html.Hidden("id", item.Id)
                    <input type="submit" value="Delete" />
                }
            </td>
        </tr>
    }
</table>

<p>
    @Html.ActionLink("Create New", "CreateCategory")
</p>

app/S4sme.Web/Areas/Blog/Views/Admin/Comments.cshtml
@model IEnumerable<S4sme.Domain.Comment>
           
@{
    ViewBag.Title = "Index";
}

<h2>Category List</h2>

<table>
    <tr>
        <th>
            Content
        </th>
        <th>
            Email
        </th>
        <th>
            Author
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @item.Content
            </td>
            <td>
                @item.Email
            </td>
            <td>
                @item.Author
            </td>
            <td>
                @Html.ActionLink("Edit", "EditComment", new { id = item.Id }) |
                
                @using (Html.BeginForm("Delete", "DeleteComment", FormMethod.Post, new { style = "display:inline" })) {
                    @Html.AntiForgeryToken()
                    @Html.Hidden("id", item.Id)
                    <input type="submit" value="Delete" />
                }
            </td>
        </tr>
    }
</table>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

app/S4sme.Web/Areas/Blog/Views/Admin/EditCategory.cshtml
@model S4sme.Tasks.Blog.ViewModels.EditCategoryViewModel
           
@{
    ViewBag.Title = "Edit";
}

<h2>Category Form</h2>

@using (Html.BeginForm("EditCategory", "Admin")) {
    @Html.ValidationSummary("Please note the following:")
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Category</legend>

        @Html.HiddenFor(m => m.Category.Id)
        @Html.EditorFor(m => m.Category.Name)

        <div class="editor-label">
            @Html.LabelFor(m => m.Category.Parent)
        </div>
        <div class="editor-field">
            <!-- Manually creating dropdown because ASP.NET MVC won't handle selected-value correctly, IMO -->
            <!-- This would be a good item for a helper, which is beyond the scope of this sample. -->
            <select name="Category.Parent">
                <option value="0">-- Select Parent --</option>
                @foreach (var category in Model.AvailableCategories) {
                    <option value="@category.Id" @(category.Equals(Model.Category.Parent) ? "selected=\"selected\"" : "")>@category.Name</option>
                }
            </select>
            @Html.ValidationMessageFor(m => m.Category.Parent)
        </div>

        <p>
            <input type="submit" value="Save" /> 
            @Html.ActionLink("Cancel", "Categories")
        </p>
    </fieldset>
}

app/S4sme.Web/Areas/Blog/Views/Admin/EditComment.cshtml
@model S4sme.Tasks.Blog.ViewModels.EditCommentViewModel
           
@{
    ViewBag.Title = "Edit Comment";
}

<h2>Comment Form</h2>

@using (Html.BeginForm("EditComment", "Admin")) {
    @Html.ValidationSummary("Please note the following:")
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Comment</legend>

        @Html.HiddenFor(m => m.Comment.Id)<br />
        @Html.HiddenFor(m => m.Comment.PostFk)<br />
        Content<br />
        @Html.TextAreaFor(m => m.Comment.Content)<br />
        Email<br />
        @Html.EditorFor(m => m.Comment.Email)<br />
        Author<br />
        @Html.EditorFor(m => m.Comment.Author)<br />
        Website<br />
        @Html.EditorFor(m => m.Comment.Website)<br />
        IP<br />
        @Html.TextAreaFor(m => m.Comment.Ip)<br />
        Created Date<br />
        @Html.EditorFor(m => m.Comment.CreatedDate)<br />        
        @Html.CheckBoxFor(m => m.Comment.IsApproved) Approved?<br />
        @Html.CheckBoxFor(m => m.Comment.IsDeleted) Deleted?<br />
        @Html.CheckBoxFor(m => m.Comment.IsDeleted) Spam?<br />

        <p>
            <input type="submit" value="Save" /> 
            @Html.ActionLink("Cancel", "Comments")
        </p>
    </fieldset>
}

app/S4sme.Web/Areas/Blog/Views/Admin/EditPost.cshtml
@model S4sme.Tasks.Blog.ViewModels.EditPostViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "../Shared/_AdminLayout.cshtml";
}

@section Stylesheets{
<link href="@Url.Content("~/Content/css/cleditor/jquery.cleditor.css")" rel="stylesheet" type="text/css" />
<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.6.2.js" type="text/javascript"></script>
<script src="@Url.Content("~/Content/js/cleditor/jquery.cleditor.min.js")" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#Post_Content").cleditor({ width: "1000px", height: "600px" });
    });
</script>
}

<h2>Post Form</h2>

@using (Html.BeginForm("EditPost", "Admin")) {
    @Html.ValidationSummary("Please note the following:")
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Post</legend>

        @Html.HiddenFor(m => m.Post.Id)
        @Html.EditorFor(m => m.Post.Title)
        @Html.EditorFor(m => m.Post.Description)
        @Html.TextAreaFor(m => m.Post.Content)

        <div class="editor-label">
            @Html.LabelFor(m => m.Post.Categories)
        </div>
        <div class="editor-field">
            @foreach (var category in Model.AvailableCategories) {
                <input id="post_Categories_@category.Id" type="checkbox" name="post.Categories" value="@category.Id" 
                    @(Model.Post.Categories.Contains(category) ? "checked=\"checked\"" : "") />
                <label for="post_Categories_@category.Id">@category.Name</label><br />
            }

            @Html.ValidationMessageFor(m => m.AvailableCategories)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.Post.Tags)
        </div>
        <div class="editor-field">
            @foreach (var tag in Model.AvailableTags) {
                <input id="post_Tags_@tag.Id" type="checkbox" name="post.Tags" value="@tag.Id" 
                    @(Model.Post.Tags.Contains(tag) ? "checked=\"checked\"" : "") />
                <label for="post_Tags_@tag.Id">@tag.Name</label><br />
            }

            @Html.ValidationMessageFor(m => m.AvailableTags)
        </div>

        <p>
            <input type="submit" value="Save" /> 
            @Html.ActionLink("Cancel", "Posts")
        </p>
    </fieldset>
}

app/S4sme.Web/Areas/Blog/Views/Admin/EditTag.cshtml
@model S4sme.Tasks.Blog.ViewModels.EditTagViewModel
           
@{
    ViewBag.Title = "Edit Tag";
}

<h2>Tag Form</h2>

@using (Html.BeginForm("EditTag", "Admin")) {
    @Html.ValidationSummary("Please note the following:")
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Tag</legend>

        @Html.HiddenFor(m => m.Tag.Id)
        @Html.EditorFor(m => m.Tag.Name)

        <p>
            <input type="submit" value="Save" /> 
            @Html.ActionLink("Cancel", "Tags")
        </p>
    </fieldset>
}

app/S4sme.Web/Areas/Blog/Views/Admin/Posts.cshtml
@model IEnumerable<S4sme.Domain.Post>
@{
    ViewBag.Title = "Index";
    Layout = "../Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>

<table>
    <tr>
        <th>
            Title
        </th>
        <th>
            Description
        </th>
        <th>
            Content
        </th>
        <th>
            Categories
        </th>
        <th>
            Tags
        </th>
        <th>
            Comments
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @item.Title
            </td>
            <td>
                @item.Description
            </td>
            <td>
                @item.Content
            </td>
            <td>
                @foreach (var category in item.Categories) {
                    @category.Name<br />
                }
            </td>
            <td>
                @foreach (var tag in item.Tags) {
                    @tag.Name<br />
                }
            </td>
            <td>
                @foreach (var comment in item.Comments) {
                    @comment.Author<br />
                    @comment.Email<br />
                    @comment.Content<br />
                }
            </td>
            <td>
                @Html.ActionLink("Edit", "EditPost", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", "Post", new { id = item.Id }, null) |

                @using (Html.BeginForm("Delete", "DeletePost", FormMethod.Post, new { style = "display:inline" })) {
                    @Html.AntiForgeryToken()
                    @Html.Hidden("id", item.Id)
                    <input type="submit" value="Delete" />
                }
            </td>
        </tr>
    }
</table>

<p>
    @Html.ActionLink("Create New", "CreatePost")
</p>


<p>@Html.Action("Categories", "Admin")</p>
<p>@Html.Action("Tags", "Admin")</p>



app/S4sme.Web/Areas/Blog/Views/Admin/Tags.cshtml
@model IEnumerable<S4sme.Domain.Tag>
           
@{
    ViewBag.Title = "Tag List";
}

<h2>Tag List</h2>

<table>
    <tr>
        <th>
            Name
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @item.Name
            </td>
            <td>
                @Html.ActionLink("Edit", "EditTag", new { id = item.Id }) |
                
                @using (Html.BeginForm("DeleteTag", "Admin", FormMethod.Post, new { style = "display:inline" })) {
                    @Html.AntiForgeryToken()
                    @Html.Hidden("id", item.Id)
                    <input type="submit" value="Delete" />
                }
            </td>
        </tr>
    }
</table>

<p>
    @Html.ActionLink("Create New", "CreateTag")
</p>